name: "Fetch GitHub Release Tag"
description: "Fetch the latest GitHub release tag unless disallowed assets are attached (e.g. .apk, .aab)."
author: "Munywele Sammy Barasa"
inputs: { }
outputs:
  tag:
    description: "The fetched release tag"
    value: ${{ steps.fetch_tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: ðŸ Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: ðŸ“¦ Install Poetry
      uses: abatilo/actions-poetry@v4

    - name: Download pyproject.toml
      run: curl -L https://raw.githubusercontent.com/masgeek/fetch-github-tag/develop/pyproject.toml -o pyproject.toml
      shell: bash

    - name: ðŸ“ Show current directory contents
      run: |
        echo "Listing files in $(pwd):"
        ls -la
      shell: bash

    - name: ðŸ’¾ Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ hashFiles('**/poetry.lock') }}

    - name: ðŸ§± Install dependencies
      run: poetry install
      shell: bash

    - name: ðŸš€ Run fetch-tag
      id: fetch_tag
      run: |
        TAG=$(poetry run fetch-tag)
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      shell: bash
