name: "Fetch GitHub Release Tag"
description: "Fetch the latest GitHub release tag unless disallowed assets are attached (e.g. .apk, .aab)."
author: "Munywele Sammy Barasa"
inputs: { }
outputs:
  tag:
    description: "The fetched release tag"
    value: "1000"

runs:
  using: "composite"
  steps:
    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: 📦 Install Poetry
      uses: abatilo/actions-poetry@v4

    - name: 💾 Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: poetry-${{ hashFiles('**/poetry.lock') }}

    - name: 🧱 Install dependencies
      run: poetry install
      shell: bash

    - name: 🚀 Run fetch-tag
      id: fetch_tag
      run: |
        TAG=$(poetry run fetch-tag)
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: 📤 Set output
      id: set_tag
      run: echo "tag=${{ steps.fetch_tag.outputs.tag }}" >> "$GITHUB_OUTPUT"
      shell: bash
