name: "Fetch GitHub Release Tag"
description: "Fetch the latest GitHub release tag unless disallowed assets are attached (e.g. .apk, .aab)."
author: "Munywele Sammy Barasa"
inputs: { }
outputs:
  tag:
    description: "The fetched release tag"
    value: ${{ steps.fetch_tag.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: 📦 Install Poetry
      uses: abatilo/actions-poetry@v4

    - name: 📦 Install CLI from wheel
      run: |
        pip install ./dist/latest_tag-*.whl
      shell: bash

    - name: 🚀 Run fetch-tag
      id: fetch_tag
      run: |
        TAG=$(poetry run fetch-tag)
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      shell: bash
